name: marketplace_analytics
version: 1.0.0
config-version: 2
profile: marketplace_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets:
  - target
  - dbt_packages
  - logs
  - warehouse

models:
  marketplace_analytics:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      finance:
        +schema: mart_finance
      product:
        +schema: mart_product
      crm:
        +schema: mart_crm

seeds:
  marketplace_analytics:
    +schema: raw
    +quote_columns: false

vars:
  cohort_spine_start: "cast('2023-01-01' as date)"
  cohort_spine_end: "cast('2025-04-01' as date)"
